apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    app: portfolio
  namespace: portfolio
spec:
  selector:
    app: my-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer