apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio
  namespace: portfolio
  labels:
    app: my-portfolio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
      - name: my-portfolio
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
      # imagePullSecrets:
      # - name: {{ .Values.imagePullSecretName }}
